btn_main_prestart = 'Accensione\nprogrammata'
btn_main_multiphase = 'Ciclo\nmultifase'
btn_main_load_from_mem = 'Carica\nprogramma'
btn_main_settings = 'Impostazioni'
prestart_set_title = 'IMP. ACCENSIONE PROGRAMMATA'
prestart_set_temp_target = 'temperatura target'
prestart_set_month = 'mese avvio:'
prestart_set_day = 'giorno avvio:'
prestart_set_hour = 'ora avvio'
prestart_set_minute = 'minuto avvio:'
prestart_set_start = 'avvio'
prestart_dash_title = 'ACCENSIONE PROGRAMMATA'

singlephase_set_title = 'IMPOSTAZIONE CICLO MONOFASE'
singlephase_set_temptarget = 'temperatura target'
singlephase_set_duration = 'durata'
time_unit = 'ore'

singlephase_dash_title = 'CICLO MONOFASE'

lo_heater_state_lbl = 'bassa potenza'
hi_heater_state_lbl = 'media potenza'
lo_hi_heater_state_lbl = 'alta potenza'
compressor_state_lbl = 'raffreddamento'
warning_out_lbl = 'controllare uscite'
warning_in_lbl = 'controllare sonde'
sleeping_lbl = 'standby'

multiphase_set_title = 'IMPOSTAZIONE CICLO MULTIFASE'
multiphase_phase1_btn = 'FASE\n1'
multiphase_phase2_btn = 'FASE\n2'
multiphase_phase3_btn = 'FASE\n3'
multiphase_phase4_btn = 'FASE\n4'
multiphase_phase5_btn = 'FASE\n5'
multiphase_program_lbl = 'programma'
multiphase_total_lbl = 'totale cicli'
multiphase_end_lbl = 'termine'

multiphase_dash_title = 'CICLO MULTIFASE'
multiphase_dash_phase = 'FASE'
program_end = 'PROGRAMMA\nTERMINATO!'

sm_notification_overwrite = 'PROGRAMMA PRESENTE.SOVRASCRIVERE?'
sm_notification_error = 'INDICARE UN NOME VALIDO!'
sm_notification_ok = 'PROGRAMMA SALVATO!'
sm_notification_delete = 'PROGRAMMA ELIMINATO!'
sm_notification_btn_cancel = 'INDIETRO'
sm_notification_btn_save = 'SALVA'
sm_notification_btn_delete = 'ELIMINA PROG'
sm_notification_btn_note = ' INSERISCI NOTE'
lm_notification_btn_load = 'CARICA PROG'

settings_title = 'IMPOSTAZIONI'
settings_lang = 'Lingua:'
settings_scale = "Scala temperatura:"
settings_offset_int = 'Offset sensore camera:'
settings_offset_ext= 'Offset sensore esterno:'
settings_wifi= 'Wi-Fi:'
settings_wifi_btn= 'sistema...'
settings_log='Log:'
settings_fw='Versione FW:'
settings_increment_temp = 'Incremento temperatura:'
settings_buzzer = 'Buzzer:'
settings_notify_ok = 'Impostazioni salvate. Riavviare app'
settings_id_sens_int = 'ID sensore camera:'
settings_id_sens_ext = 'ID sensore esterno:'
settings_sounds = 'Volume audio:'
settings_cloud = 'Cloud:'